### ISSUE TITLE
Not exposing MongoDB count({ applySkipLimit: true }) and/or size()

### ISSUE THREAD

**Issue by pvujic** [RobThree/MongoRepository#1]
It would be useful to expose MongoDB's count({ applySkipLimit: true }) and/or size() functions. These functions take skip() and limit() in consideration, so the queries will perform better.

**Comment by RobThree** [comment]
I don't think that would "fit" with the generic repository approach MongoRepository tries to implement and maintain. When this `count({ applySkipLimit: true })` would be exposed you'd simply put a leak in the abstraction. Maybe you should consider using the underlying [mongocsharpdriver](https://github.com/mongodb/mongo-csharp-driver) directly?

Any suggestions for implementing this in a generic approach are, as always, welcome though and I am, ofcourse, open for discussion!

**Comment by tegeek** [comment]
I think Repository pattern isn't suitable for this use case particularly. Like with every abstraction, we gain something and we lose something. With Repository pattern we lose some features of data storage layer. If we want to expose these features through Repository, it means we're leaking our data abstraction layer. 

In an ideal solution, our data layer doesn't have to be only 1 pattern. You can use Repository where it is appropriate and to gain the full advantage of Data Storage system, you can utilize MongoDB C# driver directly. In my opinion there is nothing wrong having multiple solutions within a single code base.
