### ISSUE TITLE
Post data and Entity inherit

### ISSUE THREAD

**Issue by ameilland** [RobThree/MongoRepository#10]
Hi,
I have created a model that inherits from Entity. And one that does not inherit from Entity.

The model that inherits from Entity instantiate the object but does not fill the property in the post request. See screenshots.

My model is like this:

```c#

public class EmailTransac : Entity
    {   [Required()]
        public string Name { get; set; }
        [Required()]
        public string From { get; set; }
        [Required()]
        public string Template { get; set; }
        [Required()]
        public string Subject { get; set; }
    }

    public class EmailTransacModel
    {
        [Required()]
        public string Name { get; set; }
        [Required()]
        public string From { get; set; }
        [Required()]
        public string Template { get; set; }
        [Required()]
        public string Subject { get; set; }
    }

```

With inherit of Entity

![2015-08-22 17_45_58-gleamr debugging - microsoft visual studio administrator](https://cloud.githubusercontent.com/assets/8339768/9424705/081a6e58-48f6-11e5-9a79-2d7e247b2a78.png)

Without inherit of Entity

![2015-08-22 17_47_03-gleamr debugging - microsoft visual studio administrator](https://cloud.githubusercontent.com/assets/8339768/9424706/1857f3da-48f6-11e5-939b-e7025176a7ad.png)

My Postman config

![2015-08-22 17_47_29-postman](https://cloud.githubusercontent.com/assets/8339768/9424707/1ee3e998-48f6-11e5-9bfa-633f541a8d27.png)

Any ideas how can I fix this?

Thanks,

**Comment by RobThree** [comment]
I kindly request you post questions on [Stackoverflow](http://stackoverflow.com/) or similar sites. This github repository contains code and actual *issues* and is not intended for support.

**Comment by ameilland** [comment]
Ok.

Post for the question on stack

http://stackoverflow.com/questions/32158737/mongorepository-post-data-and-entity-inherit-is-property-empty
