### ISSUE TITLE
Near queries

### ISSUE THREAD

**Issue by pottabathini** [RobThree/MongoRepository#12]
How to write near queries using this repository. I need one example that illustrates how to get the near all locations based on latitude and longitude.

and also how to achieve pagination using this repository.

Please help me as soon as possbile

**Comment by RobThree** [comment]
For coding questions please refer to [StackOverflow](http://stackoverflow.com/) or similar sites. The [MongoRepository issues tracker](https://github.com/RobThree/MongoRepository/issues) is for actual issues with MongoRepository, not support.
