### ISSUE TITLE
json serialization issue ASP.Net Web api

### ISSUE THREAD

**Issue by gdefombelle** [RobThree/MongoRepository#14]
When returning an entity object (derived from Entity) from a Web method, only the Id property is retuned; all other properties of the object are ignored in Json format (xml is ok)
I use ASP.Net Web Api Controller Class v2.1
a work araound is to set the [DataMemberAttribute] to each property to export in Json

**Comment by RobThree** [comment]
See https://github.com/RobThree/MongoRepository/issues/6 please.
