### ISSUE TITLE
Unable to write where condition on dates

### ISSUE THREAD

**Issue by bhanu7755** [RobThree/MongoRepository#17]
Hi, I'm unable to write where condition on dates. Whenever I compare the dates it was just hanging. Here is the example

 var data = postrepo.Where(x => x.CreatedDate== DateTime.Now);

**Comment by RobThree** [comment]
First of all I doubt you want that exact expression; `x.CreatedDate` seems unlikely to ever equal `DateTime.Now` (that would mean it would have to match up to 1/1000th of a millisecond or something around that order). You probably want to compare dates (something like `DateTime.Now.Date`) where you use the [Date](https://msdn.microsoft.com/en-us/library/system.datetime.date(v=vs.110).aspx) property to compare dates.

I guess the "hang" is not actually a hang but Mongo taking a long time finding the results you want (or expect). Did you [profile your query](https://docs.mongodb.org/v3.0/tutorial/manage-the-database-profiler/)? My best guess would be you need an [index](https://docs.mongodb.org/manual/indexes/) on the `CreatedDate` field.

**Comment by bhanu7755** [comment]
Yes.. I tried that as well 

var data = postrepo.Where(x => x.CreatedDate.Date== DateTime.Now.Date);

But the result is just same. And I have just three documents nothing more than that. Index should not be a problem.

**Comment by RobThree** [comment]
> Yes.. I tried that as well

Tried *what* as well? You'll have to be a bit more specific (also see your previous issue). I can only help you if you provide enough information (read your issues as if you know nothing about the problem or what you're doing) and also provide a test-case to reproduce or at the very least steps to reproduce the problem.

**Comment by RobThree** [comment]
I created a testcase which works fine:

```c#
using MongoRepository;
using System;
using System.Linq;

class Program
{
    static void Main(string[] args)
    {
        var postrepo = new MongoRepository<Post>();

        postrepo.Add(new Post() { CreateDate = DateTime.Now, Title = "A" });
        postrepo.Add(new Post() { CreateDate = DateTime.Now.AddDays(-1), Title = "B" });
        postrepo.Add(new Post() { CreateDate = DateTime.Now.AddHours(-2), Title = "C" });

        var todaysposts = postrepo.Where(p => p.CreateDate > DateTime.Now.Date && p.CreateDate < DateTime.Now.Date.AddDays(1));
    }
}

class Post : Entity
{
    public string Title { get; set; }
    public DateTime CreateDate { get; set; }
}
```

It turns out (as [I guessed](https://github.com/RobThree/MongoRepository/issues/17#issuecomment-154989721)) that using the `.Date` property doesn't work (driver throws a `NotSupportedException`, as expected/guessed): `An unhandled exception of type 'System.NotSupportedException' occurred in MongoDB.Driver.dll` So I implemented the other solution / workaround I provided and this works fine.

**Comment by bhanu7755** [comment]
Hi Rob, I'm sorry if i'm not clear. I tried the same approach you gave in the above example but my debug point is just disappeared at the below statement

 var todaysposts = postrepo.Where(p => p.CreateDate.Date ==start.Date
            && p.CreateDate.Date == end.Date);

**Comment by RobThree** [comment]
> but my debug point is just disappeared at the below statement

I'm sorry but I have *no* idea what that means. Do you get an exception?

> `var todaysposts = postrepo.Where(p => p.CreateDate.Date ==start.Date
&& p.CreateDate.Date == end.Date);`

That is **not** what I suggested. [My suggestion](https://github.com/RobThree/MongoRepository/issues/17#issuecomment-155056367) was:

> ```c#
var start = DateTime.Now.Date;
var end = start.AddDays(1);
>
var todaysposts = postrepo.Where(p => p.CreateDate > start 
        && p.CreateDate < end);
```
