### ISSUE TITLE
Auth connection string.

### ISSUE THREAD

**Issue by hrnkrdnz** [RobThree/MongoRepository#26]
Hi Everyone,

I can't run auth connection string. I can connect with any mongodb Gui editor or mongo.exe but Mongorepository always gives error "Command 'authenticate' failed: auth failed (response: { "ok" : 0.0, "errmsg" : "auth failed", "code" : 18 })". My connection string format is "mongodb://user:pass@localhost/DbName",

What is the problem? Thanks.

**Comment by RobThree** [comment]
Can you please post the version(s) of MongoDB, the driver you're using and MongoRepository? I'm using a similar setup in several places and have no problem connecting like this. Also: did you make sure the user is assigned to the correct DB?
