### ISSUE TITLE
Support for embedded document update

### ISSUE THREAD

**Issue by zhujinhu21** [RobThree/MongoRepository#29]
i have collection like this.

```
{
  "_id": ObjectId("554e05dfc90d3d4dfcaa2aea"),
  "username": "bodrum",
  "followerList": [
    {
      "_id": ObjectId("554e0625a51586362c33c6df"),
      "follower": "fethiye",
      "avatar": "fethiye.png"
    },
    {
      "_id": ObjectId("554e0625a51586362c33c6df"),
      "follower": "izmir",
      "avatar": "izmir.png"
    }
  ]
} 
```
 I want to remove first follower named as fethiye by follower field.

**Comment by RobThree** [comment]
See [the unittests](https://github.com/RobThree/MongoRepository/blob/master/MongoRepositoryTests/RepoTests.cs#L174). Instead of `StartsWith` use `==` or `.Equals()`.

**Comment by RobThree** [comment]
Retrieve the document, access the `followerList` property, update the document.
