### ISSUE TITLE
Nuget package dependencies for 1.3.0 need some correction

### ISSUE THREAD

**Issue by slowkot** [RobThree/MongoRepository#30]
Please correct Nuget definition for [1.3.0](https://www.nuget.org/packages/MongoRepository/1.3.0) version 

Current dependencies:
        mongocsharpdriver (**>**= 1.4.1)

Expected dependencies:
        mongocsharpdriver (**=** 1.4.1)

**Comment by RobThree** [comment]
A nuget package can't retroactively be changed (aside the title and some other meta-data) AFAIK; is there a specific reason why you're on 1.3.0 anyway? Why not use any of the later versions (which, mostly, are fixed to specific mongocsharpdriver versions).

**Comment by slowkot** [comment]
I use the latest package, but the case is following:
Each version requires strongly defined version of mongosharpdriver (e.g. latest one requires = 1.10.1 which is outdated) except MongoRepository 1.3.0 (it has >= 1.4.1 dependency).
And if you decide to update mongosharpdriver to 2.2.3 Nuget downgrades MongoRepository from 1.6.10 to 1.3.0

**Comment by RobThree** [comment]
The >=2.0 driver is incompatible with MongoRepository 1.x. There's [a 2.0](https://github.com/RobThree/MongoRepository/tree/v2) version of MongoRepository in the works ([feedback / help appreciated!](https://github.com/RobThree/MongoRepository/issues/4)).

The latest 1.x version of the mongocsharpdriver is [1.11](https://www.nuget.org/packages/mongocsharpdriver/1.11.0) which is 1 version (and an RC) ahead of 1.10.1. Not _[that](https://github.com/mongodb/mongo-csharp-driver/releases/tag/v1.11.0)_ exciting (although I just noticed [1.11 supports MongoDB 3.2](https://docs.mongodb.org/ecosystem/drivers/csharp/#compatibility); however: I haven't noticed any problems with 1.10.1 on MongoDB 3.2 if memory serves me correctly). I _could_ release a new 1.6.10 of MongoRepository with a dependency on 1.11. But that won't fix/change the behaviour you see now.

[As said](https://github.com/RobThree/MongoRepository/issues/30#issuecomment-203429499); you can't retroactively change NuGet packages so I'm not sure what you want me to do? Any suggestions?

**Comment by slowkot** [comment]
> In fact; I just did :wink:

Wow! It is not actually needed but thanks!
Yes, I noticed that the >=2.0 driver is incompatible with MongoRepository yet but Nuget doesn't know this curious thing.
I didn't know that package owner cannot change dependencies after publishing new version.
Thanks a lot!
