### ISSUE TITLE
Mongo update array element (.NET driver 2.0)

### ISSUE THREAD

**Issue by mattcahill01** [RobThree/MongoRepository#32]
Hello,

How best i use MongoRepository in order to update an element within an Array within a Document? e.g., trying to emulate this code
http://stackoverflow.com/questions/31453681/mongo-update-array-element-net-driver-2-0

but the repo doesn't accept this:
var result = this._userRepository.Update(filter, update);

Any advice appreciated. thank you,

**Comment by mattcahill01** [comment]
Hi Guys (Rob :) ),
Any chance of some feedback?

**Comment by RobThree** [comment]
MongoRepository is based on entire documents (entities) to be updated; simply pull the entity from Mongo, make your changes to the entity/document, and Update to save again.

**Comment by mattcahill01** [comment]
I have ended up just adding this new method to the repo

  /// <summary>
        /// Upserts an entity.
        /// </summary>
        /// <param name="filter">The filter.</param>
        /// <param name="updateDefinition">The update definition.</param>
        public virtual void Update(FilterDefinition<T> filter, UpdateDefinition<T> updateDefinition)
        {
          var result = this.collection.UpdateOne(filter, updateDefinition);    
        }

**Comment by RobThree** [comment]
...which is fine but not for MongoRepository. Your Update method leaks mongo-specific stuff like `FilterDefinition` and `UpdateDefinition`. MongoRepository aims to stay as persistance-agnostic as possible so you could, in theory, easily swap it out for another persistance (as long as it implements the repository interface).

**Comment by mattcahill01** [comment]
Ah Right. Makes sense if that is the goal. I like to have a bit of both however - the nice abstracted repo but some Mongo specific goodies as well.

**Comment by RobThree** [comment]
I understand; sometimes it's nice to have your cake and eat it too :wink: But consider using an extensionmethod so you can easily 'upgrade' MongoRepository should it ever change/update.
