### ISSUE TITLE
how to insert data into collection used DBRef

### ISSUE THREAD

**Issue by zhujinhu21** [RobThree/MongoRepository#34]
I want to use DBRefs ,but I don't know how to insert into entity
![201207252021208886](https://cloud.githubusercontent.com/assets/4327149/15066528/5f974072-139c-11e6-80ee-970a68480f4b.jpg)

**Comment by RobThree** [comment]
MongoRepository doesn't explicitly support DBRef's. In that case you're probably better off using the underlying [mongo-csharp-driver](https://github.com/mongodb/mongo-csharp-driver).
