### ISSUE TITLE
Is this package supports MongoDB version 2.2.3?

### ISSUE THREAD

**Issue by prabhakarreddy1234** [RobThree/MongoRepository#36]
I updated my MongoDB.Driver to 2.2.3 from a very old version 1.x.x  and observed that so many things are broken. Like i cannot see IEntity inteface, ValidateCollectionResult, CollectionStatsResult, GetIndexesResult classes etc.

**Comment by RobThree** [comment]
The 2.x branch is not compatible with the 1.x branch.

See #4 for more information.
