### ISSUE TITLE
how to search mongodb for list of ids

### ISSUE THREAD

**Issue by zhujinhu21** [RobThree/MongoRepository#40]
2 example documents of users:

{
  "_id": ObjectId("abc"),
  "name": "Miroslav",
  "tenants": [
    "jin"
  ]
}

{
  "_id": ObjectId("abd"),
  "name": "Lothar",
  "tenants": [
    "zhu"
  ]
}
And I want to fire a single query to Mongo and get the matching documents . like sql server  select * from users where id in('abc','abd')
how MongoRepository to do. thank you.

**Comment by RobThree** [comment]
`myrepo.Where(i => new [] { "abc", "abd" }.Contains(i.Id))`

Written from the top of my head, details could slightly differ.
