### ISSUE TITLE
mongorepository update specific fields or all fields 

### ISSUE THREAD

**Issue by zhujinhu21** [RobThree/MongoRepository#41]
var newCustomer = new Customer {
                FirstName = "Steve",
                LastName = "Cornell"
            };            
// searching
            var result = repo.Where(c => c.FirstName == "Steve");

            // updating 
            newCustomer.LastName = "Castle";
            repo.Update(newCustomer);

 in the code above. Update method update one filed lastName or update all fields. 
i want to update one field lastname.

**Comment by RobThree** [comment]
MongoDB is a document-based system; by default you always update the entire document. You *can* update specific fields but MongoRepository does not support that; for that you need to use the [mongo-csharp-driver](https://github.com/mongodb/mongo-csharp-driver) directly.
