### ISSUE TITLE
MongoRepositary with  latest  MongoDB Driver

### ISSUE THREAD

**Issue by BijuK** [RobThree/MongoRepository#52]
We are using MongoRepositary  in our project   for CRUD  operation ,  Mongo Repository using mongocsharpdriver  package. Currently  MongoRepository using mongocsharpdriver   1.1.0    version , but  latest version  of  mongocsharpdriver  is also available . How  I can use  MongoRepo  with latest  MongoDriver or mongocsharpdriver   ?

**Comment by RobThree** [comment]
See #4; help is welcome, PR's even more 😉
