### ISSUE TITLE
can not use GetSingle function in MongoRepository.Net45, Version=1.6.11.0

### ISSUE THREAD

**Issue by kingder-c** [RobThree/MongoRepository#57]
![image](https://user-images.githubusercontent.com/21224114/33749951-c040f088-dc0b-11e7-8a92-507632a4e7c2.png)

**Comment by RobThree** [comment]
And now I'm supposed to magically know what's going on? Make a proper report and I'll look into it. Just dumping an image without even so much as a description of the problem or anything else is _not_ how it's done.
