### ISSUE TITLE
Serializing to JSON only returns Id

### ISSUE THREAD

**Issue by chlang76** [RobThree/MongoRepository#6]
When returning collection of Product that inherits from Entity (using web api, JSON), only Id is returned. Am I missing something?

**Comment by RobThree** [comment]
Without any code or any more information than this: I don't know and can't say. Unfortunately my crystall ball is in the shop for repairs ;)

Maybe [#1753](http://mongorepository.codeplex.com/workitem/1753) or [#1444](http://mongorepository.codeplex.com/workitem/1444) contain useful information for you? If not, please open a new issue explaining clearly what you're doing, what you're trying to achieve, what the expected results are and what *actually* happens. Also please provide a testcase whenever possible to reproduce and/or demonstrate the issue.
