### ISSUE TITLE
MongoServer lifecycle

### ISSUE THREAD

**Issue by saille** [RobThree/MongoRepository#7]
This is half question, half bug report.

I believe there might be a significant bug in MongoRepository's management of the lifecycle of MongoServer. I believe MongoServer should be singleton/static, and the same instance should be used every time. Otherwise there's some overhead in connecting to the database with each instantiation of the repository.

Here in Util.cs:
private static MongoDatabase GetDatabaseFromUrl(MongoUrl url)
        {
            var client = new MongoClient(url);
            var server = client.GetServer(); // <---- should not be returning a new MongoServer instance!
            return server.GetDatabase(url.DatabaseName); // WriteConcern defaulted to Acknowledged
        }

See also http://stackoverflow.com/questions/10241641/what-is-the-right-way-to-manage-mongodb-connections-in-asp-net-mvc

I picked this up when looking at performance of queries - was seeing 200ms+ overhead with each new MongoRepository.

Apologies if I have misunderstood the code.

**Comment by RobThree** [comment]
See [MongoClient Connection Pooling](https://jira.mongodb.org/browse/CSHARP-1290). What goes there essentially also goes for MongoRepository since MongoRepository is merely a layer on top of the C# Driver.

> The driver will, for the most part, use the same connection settings. [...] Hence, the best practice will be to only instantiate 1 MongoClient at app startup and use that. Put it in an IoC container, create a static variable somewhere, etc... Essentially, make it a singleton. Is there any reason you are constructing a new client for every request?

**Comment by saille** [comment]
I'm just instantiating MongoRepository<T>, with a connection string argument. MongoRepository is calling Util's GetDatabaseFromUrl() on my behalf. Callstack is:
MongoRepository(connString)
Util.GetCollectionFromConnectionString<T>(connectionString)
Util<U>.GetCollectionFromConnectionString<T>(connectionString, GetCollectionName<T>())
Util<U>.GetDatabaseFromUrl(new MongoUrl(connectionString))
                .GetCollection<T>(collectionName)

from where it does this:
var client = new MongoClient(url);
var server = client.GetServer();
return server.GetDatabase(url.DatabaseName); // WriteConcern defaulted to Acknowledged

**Comment by RobThree** [comment]
I understand; but why not keep the repository alive (e.g. keep a reference around instead of instantiating a new one every time)?

**Comment by saille** [comment]
Thanks Rob. I did structure things that way for a while. I would prefer to see the dependency on a long lived MongoServer/MongoDatabase object, or a long lived MongoRepository instance made very explicit. The examples need to show that pattern of use - bear in mind many people don't use DI containers, and even if they do, they may inject a MongoRepository instance per request without thinking about it.

I managed to figure this out myself, but I know there's a lot of Mongo / .NET noobs who will fall into the trap of simply new'ing up a MongoRepository every time they need it. For your typical business application they may never notice the latency they have incurred.

**Comment by RobThree** [comment]
I am having trouble reproducing your findings; I have created a very simple test-project that

* Creates a new repository
* Adds a document/entity

In a loop:

```
using MongoRepository;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;

namespace ConsoleApplication1
{
    class Program
    {
        static void Main(string[] args)
        {
            var results = new List<TimeSpan>();
            
            for (int i = 0; i < 1000; i++)
            {
                var s = Stopwatch.StartNew();
                var repo = new MongoRepository<Customer>();
                repo.Add(new Customer { Name = Guid.NewGuid().ToString("N") });
                results.Add(s.Elapsed);
            }

            Trace.WriteLine(string.Format("Average: {0}", TimeSpan.FromTicks((long)results.Average(r => r.Ticks))));
            Trace.WriteLine(string.Format("Total  : {0}", TimeSpan.FromTicks((long)results.Sum(r => r.Ticks))));
        }
    }

    class Customer : Entity
    {
        public string Name { get; set; }
    }
}
```

My output is:

```
Average: 00:00:00.0004114
Total  : 00:00:00.4114397
```

There's much to say about this test-case (as it doesn't take "warmup" into account, has a abysmal way of measuring etc. etc.) but as you can see my results are very different than from what you are seeing.

Are you sure you're not doing very expensive/slow DNS lookups? Or connecting to a high-latency host? Maybe something other network related?
