### ISSUE TITLE
Add new methods to MongoRepository

### ISSUE THREAD

**Issue by ameilland** [RobThree/MongoRepository#9]
Hi,

I would like to exetend the standard MongoRepository class.
I try to inherit from `MongoRepository<t>`.

`public class CustomMongoRepository<T> : MongoRepository<T>{}`

 but it does not work.

Is it possible to do it?

I would like to add some standard methods such as AddOrUpdate(string key) ...

Thanks,

**Comment by RobThree** [comment]
Define "does not work". What doesn't work? I *think* your problem is you're missing the [generic constraint](https://msdn.microsoft.com/en-us/library/d5x73970.aspx) `where T : IEntity<TKey>`.

Also, the `Update` method is, effectively, an `AddOrUpdate` method.

**Comment by ameilland** [comment]
Great. It works. Thanks.
